version: '2'

# This compose file allows for local testing of the Gru and Minion nodes without incurring 
# costs from AWS.  Edit the docker-compose.yml file and replicate the links, environment 
# and minionN sections to increase the number of Minions to test.

services:
  gru:
    build: .
    image: smithmicro/jmeter:latest
    volumes:
      - ../plans:/plans
      - ./logs:/logs
    command: "/plans/demo.jmx"
    links: 
      - minion1
      - minion2
      - minion3
    environment: 
      - MINION_HOSTS=minion1,minion2,minion3
      - JMETER_FLAGS=-X
    ports:
      - "4445:4445/udp"
  minion1:
    image: smithmicro/jmeter:latest
  minion2:
    image: smithmicro/jmeter:latest
  minion3:
    image: smithmicro/jmeter:latest
